-- 3. Tạo bảng invoices để lưu hóa đơn
CREATE TABLE IF NOT EXISTS `invoices` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `invoice_number` varchar(20) NOT NULL UNIQUE,
  `dine_in_order_id` int(11) NOT NULL,
  `adult_count` int(11) DEFAULT 0,
  `child_count_tier1` int(11) DEFAULT 0,
  `child_count_tier2` int(11) DEFAULT 0,
  `child_count_free` int(11) DEFAULT 0,
  `buffet_subtotal` decimal(10,2) NOT NULL DEFAULT 0.00,
  `additional_charges` json DEFAULT NULL,
  `additional_charges_total` decimal(10,2) DEFAULT 0.00,
  `total_amount` decimal(10,2) NOT NULL,
  `tax_amount` decimal(10,2) DEFAULT 0.00,
  `discount_amount` decimal(10,2) DEFAULT 0.00,
  `payment_method` varchar(50) DEFAULT NULL,
  `payment_status` enum('pending','paid','cancelled') DEFAULT 'pending',
  `notes` text DEFAULT NULL,
  `issued_by` int(11) NOT NULL,
  `issued_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_invoice_dine_in_order` (`dine_in_order_id`),
  KEY `idx_invoice_number` (`invoice_number`),
  KEY `idx_issued_by` (`issued_by`),
  CONSTRAINT `fk_invoice_dine_in_order` FOREIGN KEY (`dine_in_order_id`) REFERENCES `dine_in_orders` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_invoice_issued_by` FOREIGN KEY (`issued_by`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
